# Generated by Django 5.2.8 on 2026-01-03 04:17

import django.db.models.deletion
import simple_history.models
import solicitudes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='solicitudes.comentariosolicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioSolicitudArchivoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_anexo', models.FileField(upload_to=solicitudes.models.ComentarioSolicitudArchivoAnexo.comentario_anexo_path)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_solicitud', to='solicitudes.comentariosolicitud')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalComentarioSolicitudArchivoAnexo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('archivo_anexo', models.TextField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('comentario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.comentariosolicitud')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical comentario solicitud archivo anexo',
                'verbose_name_plural': 'historical comentario solicitud archivo anexos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSolicitud',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_GESTION_MP', 'En Gestión (Mesa de Partes)'), ('REENVIO_MP', 'Reenvío a Mesa de Partes'), ('ENVIADO_A_AREA', 'Enviado a Área Encargada'), ('EN_TRAMITE_AREA', 'En Trámite (Área)'), ('CERRADO', 'Cerrado')], default='EN_GESTION_MP', max_length=20)),
                ('finalizado', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('expediente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='expedientes.expediente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_asignado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical solicitud',
                'verbose_name_plural': 'historical solicituds',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_GESTION_MP', 'En Gestión (Mesa de Partes)'), ('REENVIO_MP', 'Reenvío a Mesa de Partes'), ('ENVIADO_A_AREA', 'Enviado a Área Encargada'), ('EN_TRAMITE_AREA', 'En Trámite (Área)'), ('CERRADO', 'Cerrado')], default='EN_GESTION_MP', max_length=20)),
                ('finalizado', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='solicitud', to='expedientes.expediente')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_modificada', to=settings.AUTH_USER_MODEL)),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUsuarioSolicitudAdjuntado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'historical usuario solicitud adjuntado',
                'verbose_name_plural': 'historical usuario solicitud adjuntados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalComentarioSolicitud',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.comentariosolicitud')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'historical comentario solicitud',
                'verbose_name_plural': 'historical comentario solicituds',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='comentariosolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_solicitud', to='solicitudes.solicitud'),
        ),
        migrations.CreateModel(
            name='SolicitudArchivoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_anexo', models.FileField(upload_to=solicitudes.models.SolicitudArchivoAnexo.solicitud_anexo_path)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_archivo_anexo', to='solicitudes.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSolicitudAdjuntado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_solicitud_adjuntado', to='solicitudes.solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
